# Generated by Django 4.2.7 on 2024-05-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_request_class_duration_request_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
