# Generated by Django 4.2.7 on 2024-05-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_alter_topic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.request'),
        ),
    ]
